# This file was generated by GoReleaser. DO NOT EDIT.
cask "article_spawner" do
  version "1.1.0"

  on_macos do
    on_intel do
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/article_spawner_#{version}_darwin_amd64.tar.gz"
      sha256 "f55b652b2a8b27a0232ff176d551b1c5b40a42112427909be9b43a6582054e78"
    end
    on_arm do
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/article_spawner_#{version}_darwin_arm64.tar.gz"
      sha256 "b72b18a3e7b17364d4a525f13adde8cab94342f566ff159aabe4318f108f2dfd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/article_spawner_#{version}_linux_amd64.tar.gz"
      sha256 "de3101a99f19f1744e748d07eb29d8eff27a2f097fcb17aaa7d0296588a10b89"
    end
    on_arm do
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/article_spawner_#{version}_linux_arm64.tar.gz"
      sha256 "862698610ed441c9600cc1da05c5baa3258597843428c9ecd359b2602220c173"
    end
  end

  name "article_spawner"
  desc "Pick and open a random article from configured sources."
  homepage "https://github.com/yagnikpt/sys_tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "article_spawner"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/article_spawner"]
    end
  end

  # No zap stanza required

end
