# This file was generated by GoReleaser. DO NOT EDIT.
cask "article_spawner" do
  version "1.1.1"

  on_macos do
    on_intel do
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/article_spawner_#{version}_darwin_amd64.tar.gz"
      sha256 "fef3ac68c0e87d91d9c07afbbc79b1f5a8217f56323e03824cc688bc2bcaa2b1"
    end
    on_arm do
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/article_spawner_#{version}_darwin_arm64.tar.gz"
      sha256 "7b9589c488580a150f15ed8bb6a5c66cccb2d7dce9f353545ad702410cf78877"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/article_spawner_#{version}_linux_amd64.tar.gz"
      sha256 "b32d2cd00e9fa3be41223fb085473e88a6d71f1c87b6a61d7bf811a8a9ef6095"
    end
    on_arm do
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/article_spawner_#{version}_linux_arm64.tar.gz"
      sha256 "6bcc2f9f7b89ad95a86848bf2b3f2e010ca7cd149dd927ff2ed876829014379e"
    end
  end

  name "article_spawner"
  desc "Pick and open a random article from configured sources."
  homepage "https://github.com/yagnikpt/sys_tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "article_spawner"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/article_spawner"]
    end
  end

  # No zap stanza required

end
