# This file was generated by GoReleaser. DO NOT EDIT.
cask "bmark" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "f9d36e1e68136f18200bfa3ae8c260dcbed8807f14d0efe1aecd2527535a8e72"
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/bmark_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "138cb96373ca0ebc0fd09810e8d0552d5dd99c694164f8c2eea2232874db03db"
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/bmark_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9188322f1e3401b4d804fe875d0865ef80d312a8f89bc8036132564ba566950c"
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/bmark_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "69c46f60aef015496ee1c9a10d4358b32f57c10e0e39284f7d1838bc81a670d2"
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/bmark_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bmark"
  desc "Track reading progress for local PDF/EPUB files and reopen from the last page."
  homepage "https://github.com/yagnikpt/sys_tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bmark"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bmark"]
    end
  end

  # No zap stanza required

end
