# This file was generated by GoReleaser. DO NOT EDIT.
cask "bmark" do
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/bmark_#{version}_darwin_amd64.tar.gz"
      sha256 "f5e9801802c3eefd0184a9bb7c1d1236bcf31e8863ef085c5bc55bdcfc8f692b"
    end
    on_arm do
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/bmark_#{version}_darwin_arm64.tar.gz"
      sha256 "6ab8e28acf21c29208c8e2db4e4a0ce58f8eb358fa28334edf9946f01f29db79"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/bmark_#{version}_linux_amd64.tar.gz"
      sha256 "071b5e984b7a93e58ec29a99ab745b11a49902e211582586c0169486db50bca6"
    end
    on_arm do
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/bmark_#{version}_linux_arm64.tar.gz"
      sha256 "706bfa00d5189ce66b39774d151dfc148671ab96c30a635d3c2087bb3467295f"
    end
  end

  name "bmark"
  desc "Track reading progress for local PDF/EPUB files and reopen from the last page."
  homepage "https://github.com/yagnikpt/sys_tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bmark"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bmark"]
    end
  end

  # No zap stanza required

end
