# This file was generated by GoReleaser. DO NOT EDIT.
cask "bmark" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "867d171bb09d72fa7f81c625de01208d6ad8eb3acb06db5673f15b0ee614012d"
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/bmark_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b2eb0261ce8303f4a51a01c1dee4d77367fa0264a0426e721b8f895b67c9ae58"
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/bmark_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bc3b2cd29f2d450ee06d58828e16044f142e5268935f596c13a79a8454db21b7"
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/bmark_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0120373b7337c908cecd566c282cb9774ec8a779aab92ad5bbe5a180b2a436c7"
      url "https://github.com/yagnikpt/sys_tools/releases/download/v#{version}/bmark_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bmark"
  desc "Track reading progress for local PDF/EPUB files and reopen from the last page."
  homepage "https://github.com/yagnikpt/sys_tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bmark"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bmark"]
    end
  end

  # No zap stanza required

end
