# This file was generated by GoReleaser. DO NOT EDIT.
cask "boomtypr" do
  name "boomtypr"
  desc "A sleek typing test experience in terminal"
  homepage "https://github.com/yagnikpt/boomtypr"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boomtypr"

  on_macos do
    on_intel do
      url "https://github.com/yagnikpt/boomtypr/releases/download/v#{version}/boomtypr_Darwin_x86_64.tar.gz"
      sha256 "457d314cb0318c44996fab9b5f57afa3e78c884d35bb971c5916aceff6cc9954"
    end
    on_arm do
      url "https://github.com/yagnikpt/boomtypr/releases/download/v#{version}/boomtypr_Darwin_arm64.tar.gz"
      sha256 "b06e2e9fd155f26f17680d73f2a996c066c02a7eb51063dc9ab9a3b6232563c2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yagnikpt/boomtypr/releases/download/v#{version}/boomtypr_Linux_x86_64.tar.gz"
      sha256 "9d82694e5ac8971b52ecd4a7ed7112d3ee5d39815b406e85d2d565a3918c078e"
    end
    on_arm do
      url "https://github.com/yagnikpt/boomtypr/releases/download/v#{version}/boomtypr_Linux_arm64.tar.gz"
      sha256 "df99b445a543a02e6e2ca76041f4d2447aa7c7ff394a5af03a57fc6e0dbb2a07"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/boomtypr"]
    end
  end

  # No zap stanza required
end
