# This file was generated by GoReleaser. DO NOT EDIT.
cask "boomtypr" do
  name "boomtypr"
  desc "A sleek typing test experience in terminal"
  homepage "https://github.com/yagnikpt/boomtypr"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boomtypr"

  on_macos do
    on_intel do
      url "https://github.com/yagnikpt/boomtypr/releases/download/v#{version}/boomtypr_Darwin_x86_64.tar.gz"
      sha256 "36a6b6a82c4cbaf1f527c7aab7413f098acab85e0dcdc4145f11dad10ef7a86d"
    end
    on_arm do
      url "https://github.com/yagnikpt/boomtypr/releases/download/v#{version}/boomtypr_Darwin_arm64.tar.gz"
      sha256 "641db49551970a91f5e115623d9dc57582946bc115e308c3abb81e6f1daf0968"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yagnikpt/boomtypr/releases/download/v#{version}/boomtypr_Linux_x86_64.tar.gz"
      sha256 "bbb20fb4ec226f6b870d67e7c2193e229c3d832b9470305c4a570cb238340bb0"
    end
    on_arm do
      url "https://github.com/yagnikpt/boomtypr/releases/download/v#{version}/boomtypr_Linux_arm64.tar.gz"
      sha256 "7ad5c1f573f7e3bb145c9c3f9cf2166e7c66e9dc8ff0faad19a162616ea7b03a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/boomtypr"]
    end
  end

  # No zap stanza required
end
