# This file was generated by GoReleaser. DO NOT EDIT.
cask "boomtypr" do
  name "boomtypr"
  desc "A sleek typing test experience in terminal"
  homepage "https://github.com/yagnikpt/boomtypr"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boomtypr"

  on_macos do
    on_intel do
      url "https://github.com/yagnikpt/boomtypr/releases/download/v#{version}/boomtypr_Darwin_x86_64.tar.gz"
      sha256 "497fc9c1469c387c73bc36190237f262ef1970ffbc0679aa53b2188c66d746ef"
    end
    on_arm do
      url "https://github.com/yagnikpt/boomtypr/releases/download/v#{version}/boomtypr_Darwin_arm64.tar.gz"
      sha256 "8c5e69a8f2b8d32a9e51764378d1c35732ce9815c46dff6d38df708ec54144e5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yagnikpt/boomtypr/releases/download/v#{version}/boomtypr_Linux_x86_64.tar.gz"
      sha256 "7aaf9b4ef98129b6d9f576aae398a95e3e2eaa04e4e4d70b4856069101913393"
    end
    on_arm do
      url "https://github.com/yagnikpt/boomtypr/releases/download/v#{version}/boomtypr_Linux_arm64.tar.gz"
      sha256 "997ec6f4159a14e180c2cd962403703de7801e2cb48bbc58e53e0ed0149f2e4a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/boomtypr"]
    end
  end

  # No zap stanza required
end
