# This file was generated by GoReleaser. DO NOT EDIT.
cask "flashback" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "22a90b801c43e72f98b9b4ce262c8aed8b94327ad167ba6f728ffc717bd32289"
      url "https://github.com/yagnikpt/flashback/releases/download/v#{version}/flashback_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e09e267d93998101919f00d4d03d65e1effbb28bfcec3ad9297d66d7fd4a1faf"
      url "https://github.com/yagnikpt/flashback/releases/download/v#{version}/flashback_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "133f8f2c9d0c7c0b17b99d6c32e06ef2dc42884b05e6f7a55e5346ac0f04bbe7"
      url "https://github.com/yagnikpt/flashback/releases/download/v#{version}/flashback_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d1932cc6e9250e2d3c293b3700d4c4fcf7d3f0eaa5fe94e9091d7cb0b679aef8"
      url "https://github.com/yagnikpt/flashback/releases/download/v#{version}/flashback_Linux_arm64.tar.gz"
    end
  end

  name "flashback"
  desc "A command-line knowledge store."
  homepage "https://github.com/yagnikpt/flashback"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flashback"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flashback"]
    end
  end

  # No zap stanza required

end
