# This file was generated by GoReleaser. DO NOT EDIT.
cask "flashback" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "77cf65e54e66c7933a2e4a03e2f0d6dad98d004412bfdce43c80706ae9b17a46"
      url "https://github.com/yagnikpt/flashback/releases/download/v#{version}/flashback_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b45e5a297220bf486fa2ddbccbbfc6de3bcd1e7be0c683715f9ee79f7443ce3f"
      url "https://github.com/yagnikpt/flashback/releases/download/v#{version}/flashback_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f520f6a4560036d13bb91f2adfd2827cbfdfb7b2ab57910330e9cacf6e4d4a81"
      url "https://github.com/yagnikpt/flashback/releases/download/v#{version}/flashback_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ecbf06cb8632a91a546b1933d39f071d24067188790bfc306609655f15b06ebe"
      url "https://github.com/yagnikpt/flashback/releases/download/v#{version}/flashback_Linux_arm64.tar.gz"
    end
  end

  name "flashback"
  desc "A command-line knowledge store."
  homepage "https://github.com/yagnikpt/flashback"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flashback"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flashback"]
    end
  end

  # No zap stanza required

end
