# This file was generated by GoReleaser. DO NOT EDIT.
cask "flashback" do
  name "flashback"
  desc "A command-line knowledge store."
  homepage "https://github.com/yagnikpt/flashback"
  version "0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flashback"

  on_macos do
    on_intel do
      url "https://github.com/yagnikpt/flashback/releases/download/v#{version}/flashback_Darwin_x86_64.tar.gz"
      sha256 "4e1fc785ca1753142eb9b050ecb373057e3bcbb168fd97be9003f0d7b31635b2"
    end
    on_arm do
      url "https://github.com/yagnikpt/flashback/releases/download/v#{version}/flashback_Darwin_arm64.tar.gz"
      sha256 "019b7eee4124e82df8f8ce90f196ca19447c68dc2b55abc3e2b27b8dc6b89028"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yagnikpt/flashback/releases/download/v#{version}/flashback_Linux_x86_64.tar.gz"
      sha256 "794afba6f26ef002f6501c47edeba55d679c330ecfd41b568cc8d82b92700905"
    end
    on_arm do
      url "https://github.com/yagnikpt/flashback/releases/download/v#{version}/flashback_Linux_arm64.tar.gz"
      sha256 "c02455fbd7bf1dbfef11978310021a82eb4cfec0d348c31ca4c26d8fedc05e6e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flashback"]
    end
  end

  # No zap stanza required
end
