# This file was generated by GoReleaser. DO NOT EDIT.
cask "whrelay" do
  name "whrelay"
  desc "A lightweight, self-hosted webhook relay server."
  homepage "https://github.com/yagnikpt/webhook-relay"
  version "0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "whrelay"

  on_macos do
    on_intel do
      url "https://github.com/yagnikpt/webhook-relay/releases/download/v#{version}/webhook-relay_Darwin_x86_64.tar.gz"
      sha256 "821500afad6ee39bd432c3cbe979885c69fed7001db8cbf241b7fd4fdd7d2dcd"
    end
    on_arm do
      url "https://github.com/yagnikpt/webhook-relay/releases/download/v#{version}/webhook-relay_Darwin_arm64.tar.gz"
      sha256 "eb1fdaf28e1ef9651aba536901c6ccb65825092be3f667916e06cc5b79fe7e8a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yagnikpt/webhook-relay/releases/download/v#{version}/webhook-relay_Linux_x86_64.tar.gz"
      sha256 "65ab28b74179055545967b5db1908dceeee9bf7f6a8a92cf6dc3499712f27364"
    end
    on_arm do
      url "https://github.com/yagnikpt/webhook-relay/releases/download/v#{version}/webhook-relay_Linux_arm64.tar.gz"
      sha256 "3908df73d407a990060946cc661d587cfd053f64887d347b4103c3e0b6890625"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/whrelay"]
    end
  end

  # No zap stanza required
end
