# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Tpaper < Formula
  desc "Terminal-based note-taking app built around the idea of buffers and blocks"
  homepage "https://github.com/yagnikpt/tpaper"
  url "https://github.com/yagnikpt/tpaper/archive/refs/tags/v0.2.1.tar.gz"
  sha256 "16ad206e2ab1652f80a3618bf2f7e90c9e00b36a1a88ed84fcbc08b57faec3d5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/yagnikpt/tpaper/releases/download/v0.2.1/tpaper-0.2.1-darwin-amd64.tar.gz"
      sha256 "954ee3b2b7701943bfa56cfebc05dcb2e8ccd6006013c777a8f62d36955a8546"
    end

    on_arm do
      url "https://github.com/yagnikpt/tpaper/releases/download/v0.2.1/tpaper-0.2.1-darwin-arm64.tar.gz"
      sha256 "8c24aa8442a966fe90d86269d2a55aaf3943c9b562a6b6d93e1b3f48dbb2c3a7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yagnikpt/tpaper/releases/download/v0.2.1/tpaper-0.2.1-linux-amd64.tar.gz"
      sha256 "b11812d78386b064b7f1aa295a7ad00992665862f66c9b92bfc027967df2256d"
    end

    on_arm do
      url "https://github.com/yagnikpt/tpaper/releases/download/v0.2.1/tpaper-0.2.1-linux-arm64.tar.gz"
      sha256 "468be96267fd4dac24110c1807dd621c87bd716eec36a7086ab5adb354da13d9"
    end
  end

  def install
    bin.install "tpaper"
  end

  test do
    assert_predicate bin/"tpaper", :exist?
  end
end
