# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Tpaper < Formula
  desc "Terminal-based note-taking app built around the idea of buffers and blocks"
  homepage "https://github.com/yagnikpt/tpaper"
  url "https://github.com/yagnikpt/tpaper/archive/refs/tags/0.1.0.tar.gz"
  version "0.1.0"
  sha256 "9a6e9187e61b8720609f3e70ed3c63f0f231d1f845b739d8c1cb191d0e00cc29"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/yagnikpt/tpaper/releases/download/0.1.0/tpaper-0.1.0-darwin-amd64.tar.gz"
      sha256 "dcd052997d39ecd11869c2087d9b6d5e55690e7446f0092815e27b7e2a9d5f5f"
    end

    on_arm do
      url "https://github.com/yagnikpt/tpaper/releases/download/0.1.0/tpaper-0.1.0-darwin-arm64.tar.gz"
      sha256 "4549d63c0d8555e67d9648adde3612386b744a64442c3eb515857d53804400fd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yagnikpt/tpaper/releases/download/0.1.0/tpaper-0.1.0-linux-amd64.tar.gz"
      sha256 "2a1a6d6e56cc67a41ab43795ad234151aacaee6c21b7054cd2954e20043fbd65"
    end

    on_arm do
      url "https://github.com/yagnikpt/tpaper/releases/download/0.1.0/tpaper-0.1.0-linux-arm64.tar.gz"
      sha256 "4b70d909e9e946c7520576cd7748e51691bd258022718665ded831be8f13225e"
    end
  end

  def install
    bin.install "tpaper"
  end

  test do
    assert_predicate bin/"tpaper", :exist?
  end
end
